#Конфигурация праивл классификации
#Идея в том что категории и ключевые слова лучше харнить отдельно от кода
#Плюс в том что становится легче менять правила и можно показать на защите что класификация настраиваемая
